name: CI 
on: [workflow_dispatch]
jobs:   
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Get Hash
      id: hash
      #run: echo "git_hash=$(git rev-parse | -c 1-6)"
      run: echo ::set-output name=VERSION::$(echo git rev-parse | -c 1-6)

    - name: Check Hash
      run: echo "${{ env.hash }}"
